inputs_def:
  - handle: images
    description: Input
    json_schema:
      type: array
      items:
        type: string
    value:
      []
  - handle: key
    json_schema:
      contentMediaType: oomol/secret
      type: string
  - handle: save_address
    json_schema:
      type: string
      ui:widget: dir
    value:
    nullable: true
outputs_def:
  - handle: save_images
    description: Output
    json_schema:
      type: array
      items:
        type: string
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: Remove Images BG
icon: ":fa6-solid:images:"
