inputs_def:
  - handle: image
    description: Input
    json_schema:
      type: string
      ui:widget: file
  - handle: key
    json_schema:
      contentMediaType: oomol/secret
      type: string
  - handle: save_address
    json_schema:
      type: string
      ui:widget: dir
outputs_def:
  - handle: save_image
    description: Output
    json_schema:
      type: string
      ui:widget: file
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: Remove BG
icon: ":fa6-solid:id-badge:"
